version: "3.1"
networks:
  mysql_default:
    external: true
    
services:
  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    ports:
      - "80:80"
    networks:
      - mysql_default

  php-fpm:
    build: phpdocker/php-fpm
    container_name: symfony-php-fpm
    working_dir: /application
    volumes:
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - .:/application
      - .:/vendor
    networks:
      - mysql_default
